### ISSUE TITLE
Dread: BMTRE's don't build properly

### ISSUE THREAD

**Issue by Miepee** [randovania/mercury-engine-data-structures#173]
`FAILED tests/formats/test_bmtre.py::test_bmtre_dread[actors/characters/autclast/scripts/autclast.bmtre] - construct.core.SelectError: Error in path (building) -> behavior -> type
no subconstruct matched: behaviortree::CRepeat`
Whatever PR fixes this, should also add tests.

**Comment by steven11sjf** [comment]
"wait who the hell used a select there, that makes no sense!?!"
> git blames

oop
