### ISSUE TITLE
Tests skipped for missing files

### ISSUE THREAD

**Issue by steven11sjf** [randovania/mercury-engine-data-structures#30]
![image](https://user-images.githubusercontent.com/25016775/221347773-121493ce-2ca6-4ca2-a3a3-5eaf7468e042.png)

Five tests are skipped due to missing files: `walktailinit.bmbls`, `itemsphere_plasmabeam.bmsad`, `s060_quarantine.bmssd`, `s090_skybase.brfld` and `s010_cave.bmmap`. According to switchtoolbox they are there so unsure why pytest cannot find them.

**Comment by Miepee** [comment]
In addition, it also can't find `s050_area5.bmssd` for MSR:
![grafik](https://github.com/user-attachments/assets/6cc8101c-f943-4779-a793-ec9b2de02153)
